#!/bin/bash
FILE=$2
TEMPFILE="$$.tmp"
declare -i ROW=0;
declare -i COL=0;

#Checks if File can be found
checkValidFile()
{
    if [ ! -f $FILE ]; then
        echo "./stats: cannot read $FILE";
        exit;
    fi
}

FillFileRow()
{
    while read line; 
    do
        echo $( for i in $line; do echo -e "$i\t";done | sort -n ) #>> $TEMPFILE
    done < $FILE;
}

FillFileCol()
{
 echo fuck;
}

rows_func() 
{
    checkValidFile;

    FillFileRow;


}

cols_func()
{
    checkValidFile; 
    
    FillFileCol;

    #Averages logic

    #Median logic

    #printArray;
}

#Main
if [ "$#" -gt 2 ] || [ "$#" -lt 1 ]
then
    echo "$0 {-rows|-cols} [file]" >&2
    exit 1;
fi
if [[ "$1" == -r* ]]
then
    rows_func;
    exit 0;
elif [[ "$1" == -c* ]] 
then
    cols_func;
    exit 0;
else
    echo "$0 {-rows|-cols} [file]" >&2
    exit 1;
fi
